name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to access all .claude and .cursor files

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            /review

            Review this pull request following the comprehensive review guidelines in .claude/commands/review.md.

            Additional context:
            1. First, use `gh pr view ${{ github.event.pull_request.number }}` to see the PR details
            2. Use `gh pr diff ${{ github.event.pull_request.number }}` to see the changes
            3. Review against the project standards in .claude/commands/project-context.md
            4. Check if new components reuse existing ones from .cursor/rules/components/COMPONENTS_REFERENCE.md

            Follow the review checklist covering:
            - Architecture & Patterns
            - React & Astro Best Practices
            - API & Backend
            - Database & Migrations
            - Styling & UI (DaisyUI/Tailwind)
            - Accessibility
            - Error Handling
            - TypeScript
            - Security
            - Performance

            Provide your review following the format specified in review.md:
            - Summary
            - Issues Found (Critical/Important/Minor)
            - Specific Feedback with line references
            - Positive Notes
            - Recommendations

            Post your review using: `gh pr comment ${{ github.event.pull_request.number }} -b "YOUR_REVIEW"`

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

